// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_currency_index from "./routes/api/currency/index.ts";
import * as $api_search_accommodation_index from "./routes/api/search/accommodation/index.ts";
import * as $api_search_accommodation_prepare_query from "./routes/api/search/accommodation/prepare-query.ts";
import * as $api_search_accommodation_results_url from "./routes/api/search/accommodation/results-url.ts";
import * as $api_search_accommodation_search_accommodation from "./routes/api/search/accommodation/search-accommodation.ts";
import * as $api_search_accommodation_search_url from "./routes/api/search/accommodation/search-url.ts";
import * as $api_search_accommodation_types from "./routes/api/search/accommodation/types.ts";
import * as $api_search_events_index from "./routes/api/search/events/index.ts";
import * as $api_search_events_normalize_event_data from "./routes/api/search/events/normalize-event-data.ts";
import * as $api_search_events_search_events from "./routes/api/search/events/search-events.ts";
import * as $api_search_events_search_venue from "./routes/api/search/events/search-venue.ts";
import * as $api_search_events_types from "./routes/api/search/events/types.ts";
import * as $api_search_flights_build_url from "./routes/api/search/flights/build-url.ts";
import * as $api_search_flights_consts from "./routes/api/search/flights/consts.ts";
import * as $api_search_flights_flights_data_from from "./routes/api/search/flights/flights-data-from.ts";
import * as $api_search_flights_geocode from "./routes/api/search/flights/geocode.ts";
import * as $api_search_flights_get_city_code from "./routes/api/search/flights/get-city-code.ts";
import * as $api_search_flights_id_from_coordinates from "./routes/api/search/flights/id-from-coordinates.ts";
import * as $api_search_flights_index from "./routes/api/search/flights/index.ts";
import * as $api_search_flights_search_flights from "./routes/api/search/flights/search-flights.ts";
import * as $index from "./routes/index.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $SearchView from "./islands/SearchView.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/currency/index.ts": $api_currency_index,
    "./routes/api/search/accommodation/index.ts":
      $api_search_accommodation_index,
    "./routes/api/search/accommodation/prepare-query.ts":
      $api_search_accommodation_prepare_query,
    "./routes/api/search/accommodation/results-url.ts":
      $api_search_accommodation_results_url,
    "./routes/api/search/accommodation/search-accommodation.ts":
      $api_search_accommodation_search_accommodation,
    "./routes/api/search/accommodation/search-url.ts":
      $api_search_accommodation_search_url,
    "./routes/api/search/accommodation/types.ts":
      $api_search_accommodation_types,
    "./routes/api/search/events/index.ts": $api_search_events_index,
    "./routes/api/search/events/normalize-event-data.ts":
      $api_search_events_normalize_event_data,
    "./routes/api/search/events/search-events.ts":
      $api_search_events_search_events,
    "./routes/api/search/events/search-venue.ts":
      $api_search_events_search_venue,
    "./routes/api/search/events/types.ts": $api_search_events_types,
    "./routes/api/search/flights/build-url.ts": $api_search_flights_build_url,
    "./routes/api/search/flights/consts.ts": $api_search_flights_consts,
    "./routes/api/search/flights/flights-data-from.ts":
      $api_search_flights_flights_data_from,
    "./routes/api/search/flights/geocode.ts": $api_search_flights_geocode,
    "./routes/api/search/flights/get-city-code.ts":
      $api_search_flights_get_city_code,
    "./routes/api/search/flights/id-from-coordinates.ts":
      $api_search_flights_id_from_coordinates,
    "./routes/api/search/flights/index.ts": $api_search_flights_index,
    "./routes/api/search/flights/search-flights.ts":
      $api_search_flights_search_flights,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Footer.tsx": $Footer,
    "./islands/SearchView.tsx": $SearchView,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
