// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/search/airbnb.ts";
import * as $1 from "./routes/api/search/kiwi.ts";
import * as $2 from "./routes/api/search/ra.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/EventAutocomplete.tsx";
import * as $$2 from "./islands/NightsCounter.tsx";
import * as $$3 from "./islands/PeopleCounter.tsx";
import * as $$4 from "./islands/SearchView.tsx";

const manifest = {
  routes: {
    "./routes/api/search/airbnb.ts": $0,
    "./routes/api/search/kiwi.ts": $1,
    "./routes/api/search/ra.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/EventAutocomplete.tsx": $$1,
    "./islands/NightsCounter.tsx": $$2,
    "./islands/PeopleCounter.tsx": $$3,
    "./islands/SearchView.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
